### ISSUE TITLE
amp-apiserver: Watch failed after playbook was deleted if still watching

### ISSUE THREAD

**Issue by wangeguo** [amphitheatre-app/amphitheatre#186]
2024-04-26T10:28:02.912317Z DEBUG Deleting Playbook: Some(PlaybookStatus { conditions: [Condition { last_transition_time: Time(2024-04-26T10:27:27Z), message: "", observed_generation: None, reason: "AutoRun", status: "True", type_: "Running" }] })
thread 'tokio-runtime-worker' panicked at apiserver/src/services/logger.rs:55:56:
called `Result::unwrap()` on an `Err` value: WatchFailed(ReadEvents(Custom { kind: Other, error: Service(hyper::Error(Body, Kind(TimedOut))) }))
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at apiserver/src/services/logger.rs:55:56:
called `Result::unwrap()` on an `Err` value: WatchFailed(ReadEvents(Custom { kind: Other, error: Service(hyper::Error(Body, Kind(TimedOut))) }))
thread 'tokio-runtime-worker' panicked at apiserver/src/services/logger.rs:55:56:
called `Result::unwrap()` on an `Err` value: WatchFailed(ReadEvents(Custom { kind: Other, error: Service(hyper::Error(Body, Kind(TimedOut))) }))
thread 'tokio-runtime-worker' panicked at apiserver/src/services/logger.rs:55:56:
called `Result::unwrap()` on an `Err` value: WatchFailed(ReadEvents(Custom { kind: Other, error: Service(hyper::Error(Body, Kind(TimedOut))) }))

**Comment by ShantelPeters** [comment]
Please can I work on this ?
